---
- name: This playbook will install apache2
  hosts: all
  become: true
  tasks:
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest

  - name: repo repo index
    apt:
      update_cache: yes
