---
- name: This playbook will install apache2
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Centos"]

  - name: add php support for apache
    apt: #is the module which we are using
      name: libapache2-mod-php
      state: latest
