---
- name: Playbook in updated format
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
  - name: update repo index for ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install apache2 and php package for unbuntu
    apt:
      name: 
        - apache2
        - libapache2-mob-php
      state: latest
    when: ansible_distribution == "Ubuntu"
